/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposdedy;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author Lenovo
 */
public class FrmBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBarang
     */
    // Perintah memanggil class DATABASE
    // Instanisasi objek (Class)
    Database db = new Database();
    public FrmBarang() {
        initComponents();
        // mengatur form ditengah-tengah layar
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setLocation(x, y);
        
        // Menghubungkan ke database
        db.koneksi();
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jkd_brg = new javax.swing.JTextField();
        jbtSimpan = new javax.swing.JButton();
        jbtBatal = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();
        jnama_brg = new javax.swing.JTextField();
        jharga = new javax.swing.JTextField();
        jjml = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtEdit = new javax.swing.JButton();
        jbtHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input Data Barang");
        setBackground(new java.awt.Color(45, 19, 216));

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Harga");

        jLabel4.setText("Jumlah Barang");

        jkd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_brgActionPerformed(evt);
            }
        });

        jbtSimpan.setText("Simpan");
        jbtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSimpanActionPerformed(evt);
            }
        });

        jbtBatal.setText("Batal");
        jbtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBatalActionPerformed(evt);
            }
        });

        jbtKeluar.setText("Keluar");
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        jnama_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnama_brgActionPerformed(evt);
            }
        });

        jharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhargaActionPerformed(evt);
            }
        });

        jjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjmlActionPerformed(evt);
            }
        });

        jLabel5.setText("Administrasi");

        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtHapus.setText("Hapus");
        jbtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jharga, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjml, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jbtBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtEdit)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jkd_brg))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnama_brg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jjml))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jharga))
                .addGap(26, 26, 26)
                .addComponent(jbtSimpan)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBatal)
                    .addComponent(jbtKeluar)
                    .addComponent(jbtEdit)
                    .addComponent(jbtHapus))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_brgActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambildata("select * from tbarang where kd_brg='" + jkd_brg.getText() + "'");
            if (rs.next()) {
                jnama_brg.setText(rs.getString("nama_brg"));
                jharga.setText(rs.getString("harga"));
                jjml.setText(rs.getString("jml"));
            } else {
                JOptionPane.showMessageDialog(null, "Data Belum terdaftar, Tambahkan");
                jnama_brg.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jkd_brgActionPerformed

    private void jbtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBatalActionPerformed
        // TODO add your handling code here:
        jkd_brg.setText("");
        jnama_brg.setText("");
        jharga.setText("");
        jjml.setText("");
    }//GEN-LAST:event_jbtBatalActionPerformed

    private void jnama_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnama_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnama_brgActionPerformed

    private void jhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhargaActionPerformed

    private void jjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjmlActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tbarang where kd_brg='"+jkd_brg.getText()+"'");
            if (rs.next()) {
                db.aksi("update tbarang set nama_brg='"+jnama_brg.getText()+"',harga='"+jharga.getText()+"',jml='"+jjml.getText()+"'"
                + "where kd_brg='"+jkd_brg.getText()+"'");
                JOptionPane.showMessageDialog(null, "Data berhasil diedit");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak adas data yang hendak di edit......");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jbtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSimpanActionPerformed
        // TODO add your handling code here:
          try {
            ResultSet rs=db.ambildata("select * from tbarang where kd_brg='"+jkd_brg.getText()+"'");
             if (rs.next()) {
                 JOptionPane.showMessageDialog(null, "Data telah terdaftar");
                 jnama_brg.setText(rs.getString("nama_brg"));
                 jharga.setText(rs.getString("harga"));
                 jjml.setText(rs.getString("jml"));
             } else {
        
                 db.aksi("insert into tbarang(kd_brg,nama_brg,jml,harga)values('"+jkd_brg.getText()+"','"+jnama_brg.getText()+"','"+jjml.getText()+"','"+jharga.getText()+"')");
                 JOptionPane.showMessageDialog(null, "Data anda berhasil disimpan");
                 jkd_brg.setText("");
                 jnama_brg.setText("");
                 jjml.setText("");
                 jharga.setText("");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        
    }                                       

           
    }//GEN-LAST:event_jbtSimpanActionPerformed

    private void jbtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tbarang where kd_brg='"+jkd_brg.getText()+"'");
            if (rs.next()) {
                int n = JOptionPane.showConfirmDialog(this, "Anda Yakin?", "RPL Massage", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null);
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from tbarang where kd_brg='"+jkd_brg.getText()+"'");
                    JOptionPane.showMessageDialog(null, "Data sudah terhapus");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak terdaftar");
            }
             jkd_brg.setText("");
             jnama_brg.setText("");
             jharga.setText("");
             jjml.setText("");
             jkd_brg.requestFocus();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jbtHapusActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Yakin keluar dari aplikasi ini?",
                "Reminder RPL", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtBatal;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtHapus;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtSimpan;
    private javax.swing.JTextField jharga;
    private javax.swing.JTextField jjml;
    private javax.swing.JTextField jkd_brg;
    private javax.swing.JTextField jnama_brg;
    // End of variables declaration//GEN-END:variables
}
