 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposdedy;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author Lenovo
 */
public class FrmKry extends javax.swing.JFrame {

    /**
     * Creates new form FrmKry
     */
    Database db = new Database();
    
    public FrmKry() {
        initComponents();
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setLocation(x, y);
        
        // Menghubungkan ke database
        db.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jkd_kry = new javax.swing.JTextField();
        jnama = new javax.swing.JTextField();
        jalamat = new javax.swing.JTextField();
        jtlp = new javax.swing.JTextField();
        jusername = new javax.swing.JTextField();
        jbtSimpan = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();
        jbtBatal = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jbtHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jjk = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jpass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Kode Karyawan");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Alamat");

        jLabel5.setText("Telepon");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        jkd_kry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_kryActionPerformed(evt);
            }
        });

        jnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnamaActionPerformed(evt);
            }
        });

        jalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalamatActionPerformed(evt);
            }
        });

        jtlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlpActionPerformed(evt);
            }
        });

        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });

        jbtSimpan.setText("Simpan");
        jbtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSimpanActionPerformed(evt);
            }
        });

        jbtKeluar.setText("Keluar");
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        jbtBatal.setText("Batal");
        jbtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBatalActionPerformed(evt);
            }
        });

        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtHapus.setText("Hapus");
        jbtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHapusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel9.setText("Menu Register Karyawan");

        jjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));

        jLabel8.setText("Pilih L jika laki-laki, Pilih P jika perempuan");

        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jbtSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jbtHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jalamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtlp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jusername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jnama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jjk, 0, 128, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jkd_kry, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpass, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkd_kry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jalamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtlp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jusername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSimpan)
                    .addComponent(jbtBatal)
                    .addComponent(jbtEdit)
                    .addComponent(jbtHapus)
                    .addComponent(jbtKeluar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkd_kryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_kryActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambildata("select * from tkaryawan where kd_kry='" + jkd_kry.getText() + "'");
            if (rs.next()) {
                jnama.setText(rs.getString("nama"));
                jjk.setSelectedItem(rs.getString("jk"));
                jalamat.setText(rs.getString("alamat"));
                jtlp.setText(rs.getString("telepon"));
                jusername.setText(rs.getString("username"));
                jpass.setText(rs.getString("password"));
            } else {
                JOptionPane.showMessageDialog(null, "Data Karyawan Belum terdaftar, Tambahkan");
                jnama.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jkd_kryActionPerformed

    private void jnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnamaActionPerformed

    private void jalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jalamatActionPerformed

    private void jtlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlpActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void jbtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBatalActionPerformed
        // TODO add your handling code here:
        jkd_kry.setText("");
        jnama.setText("");
        jjk.setSelectedItem("");
        jalamat.setText("");
        jtlp.setText("");
        jusername.setText("");
        jpass.setText("");
    }//GEN-LAST:event_jbtBatalActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
            if (rs.next()) {
                db.aksi("update tkaryawan set nama='"+jnama.getText()+"',jk='"+jjk.getSelectedItem()+"',alamat='"+jalamat.getText()+"',telepon='"+jtlp.getText()+"',username='"+jusername.getText()+"',password='"+jpass.getText()+"'"
                        + "where kd_kry='"+jkd_kry.getText()+"'");
                JOptionPane.showMessageDialog(null, "Data Karyawan berhasil diedit");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang hendak di edit......");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jbtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSimpanActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
             if (rs.next()) {
                 JOptionPane.showMessageDialog(null, "Data Karyawan telah terdaftar");
                 jnama.setText(rs.getString("nama"));
                 jjk.setSelectedItem(rs.getString("jk"));
                 jalamat.setText(rs.getString("alamat"));
                 jtlp.setText(rs.getString("telepon"));
                 jusername.setText(rs.getString("username"));
                 jpass.setText(rs.getString("password"));
             } else {
                 db.aksi("insert into tkaryawan(kd_kry,nama,jk,alamat,telepon,username,password)values('"+jkd_kry.getText()+"','"+jnama.getText()+"','"+jjk.getSelectedItem()+"','"+jalamat.getText()+"','"+jtlp.getText()+"','"+jusername.getText()+"','"+jpass.getText()+"')");
                 JOptionPane.showMessageDialog(null, "Data anda berhasil disimpan");
                 jnama.setText("");
                 jjk.setSelectedItem("");
                 jalamat.setText("");
                 jtlp.setText("");
                 jusername.setText("");
                 jpass.setText("");
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        
    }        
    }//GEN-LAST:event_jbtSimpanActionPerformed

    private void jbtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambildata("select * from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
            if (rs.next()) {
                int n = JOptionPane.showConfirmDialog(this, "Anda Yakin?", "RPL Massage", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null);
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
                    JOptionPane.showMessageDialog(null, "Data sudah terhapus");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak terdaftar");
            }
            jnama.setText("");
            jjk.setSelectedItem("");
            jalamat.setText("");
            jtlp.setText("");
            jusername.setText("");
            jpass.setText("");
            jkd_kry.requestFocus();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jbtHapusActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Yakin keluar dari aplikasi ini?",
                "Reminder RPL", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jalamat;
    private javax.swing.JButton jbtBatal;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtHapus;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtSimpan;
    private javax.swing.JComboBox<String> jjk;
    private javax.swing.JTextField jkd_kry;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jpass;
    private javax.swing.JTextField jtlp;
    private javax.swing.JTextField jusername;
    // End of variables declaration//GEN-END:variables
}
