/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposdedy;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class FrmTrans extends javax.swing.JInternalFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    long sumTotal = 0;
    
    // Panggil om om database
    Database db = new Database();

    /**
     * Creates new form FrmTrans
     */
    public FrmTrans() {
        db.koneksi();
        initComponents();
        //Mengatur form muncul ditengah
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getWidth()) / 2;
        this.setLocation(x, y);
        //Menampilkan tanggal otomatis
        tglskrg();
        //Menampilkan nomer otomatis
        buatnomor();
        //Menampilkan judul tabel
        aturTable();
        xkd_brg.requestFocus();
    }
     
    //Perintah tgl otomatis
    public void tglskrg(){
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd MMMM YYYY");
        String tanggal = format.format(skrg);
        xtanggal.setText(format.format(skrg));
    }
    
    public void buatnomor() {
        try {
            ResultSet rs = db.ambildata("Select no_trans as auto from ttrans_jual ORDER by no_trans desc");
            if (rs.next()) {
                int no_u = Integer.parseInt(rs.getString("auto")) + 1;
                xno_trans.setText(Integer.toString(no_u));
            } else {
                int no_t = 1;
                xno_trans.setText(Integer.toString(no_t));
            }
        } catch (Exception e) {
            
        }
    }
    
    public void aturTable() {
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jml Barang");
        xtable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xtanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        xno_trans = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        xkd_brg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        xnama_brg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        xstok = new javax.swing.JTextField();
        xharga = new javax.swing.JTextField();
        xjml = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        xjmlh = new javax.swing.JTextField();
        jbtTambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xtable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        xtotal = new javax.swing.JTextField();
        xbayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        xkembali = new javax.swing.JTextField();
        jbtSimpan = new javax.swing.JButton();
        jbtBatal = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 253, 210));

        jLabel1.setText("No Transaksi");

        xtanggal.setEditable(false);
        xtanggal.setBackground(new java.awt.Color(204, 204, 255));
        xtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtanggalActionPerformed(evt);
            }
        });

        jLabel2.setText("Tanggal");

        xno_trans.setEditable(false);
        xno_trans.setBackground(new java.awt.Color(204, 204, 255));
        xno_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xno_transActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Barang");

        xkd_brg.setBackground(new java.awt.Color(204, 204, 255));
        xkd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xkd_brgActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Barang");

        xnama_brg.setEditable(false);
        xnama_brg.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("Stok");

        jLabel6.setText("Harga");

        jLabel7.setText("Jumlah");

        xstok.setEditable(false);
        xstok.setBackground(new java.awt.Color(204, 204, 255));
        xstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xstokActionPerformed(evt);
            }
        });

        xharga.setEditable(false);
        xharga.setBackground(new java.awt.Color(204, 204, 255));

        xjml.setBackground(new java.awt.Color(204, 204, 255));
        xjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjmlActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah Harga");

        xjmlh.setEditable(false);
        xjmlh.setBackground(new java.awt.Color(204, 204, 255));
        xjmlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xjmlhActionPerformed(evt);
            }
        });

        jbtTambah.setText("Tambah");
        jbtTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTambahActionPerformed(evt);
            }
        });

        jLabel9.setText("Pilih item barang dibawah ini apa bila hendak membatalkan transaksi pembelian barang");

        xtable1.setBackground(new java.awt.Color(204, 204, 255));
        xtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        xtable1.setGridColor(new java.awt.Color(51, 51, 255));
        xtable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xtable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(xtable1);

        jLabel10.setText("TOTAL");

        xtotal.setEditable(false);
        xtotal.setBackground(new java.awt.Color(255, 255, 255));

        xbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbayarActionPerformed(evt);
            }
        });

        jLabel11.setText("BAYAR");

        jLabel12.setText("KEMBALI");

        xkembali.setEditable(false);
        xkembali.setBackground(new java.awt.Color(255, 255, 255));

        jbtSimpan.setText("Simpan");
        jbtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSimpanActionPerformed(evt);
            }
        });

        jbtBatal.setText("Batal");
        jbtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBatalActionPerformed(evt);
            }
        });

        jbtKeluar.setText("Keluar");
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(xno_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(xkd_brg))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(xnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xstok, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(xjmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xharga, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel6)))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(xjml)))
                            .addComponent(xtanggal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jbtSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtKeluar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel11)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel12)
                                .addGap(329, 329, 329))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xno_trans)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(xjmlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtTambah)
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtKeluar)
                    .addComponent(jbtBatal)
                    .addComponent(jbtSimpan))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void xtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xtanggalActionPerformed

    private void xno_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xno_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xno_transActionPerformed

    private void jbtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSimpanActionPerformed
        // TODO add your handling code here:
        sumTotal = 0;
        int row = xtable1.getRowCount();
        
        try {
//            ResultSet rs=db.ambildata("select * from ttrans_jual where no_trans='"+xno_trans.getText()+"'");
//            if (rs.next()) {
//                JOptionPane.showConfirmDialog(null, "No, transaksi sudah terdaftar");
//            } else {
            
            for (int i = 0; i < row; i++) {
                db.aksi("insert into tdetail_jual(no_trans,tanggal,kd_brg,jml,harga)values"
                        + "('"+xno_trans.getText()+"','"+xtanggal.getText()+"','"+xtable1.getValueAt(i, 0)+"','"+xtable1.getValueAt(i, 3)+"','"+xtable1.getValueAt(i, 2)+"')");
                
              db.aksi("update tbarang set jml=jml-" + xtable1.getValueAt(i, 3) + " where kd_brg='"+xtable1.getValueAt(i, 0)+"'");
            }
            db.aksi("insert into ttrans_jual(no_trans,tanggal,total)values('"+xno_trans.getText()+"', '"+xtanggal.getText()+"'"
                    + ", '"+xtotal.getText()+"')");
            JOptionPane.showMessageDialog(null, "Data telah tersimpan");
            
            // }
            model.setRowCount(0);
            xtotal.setText("");
            xbayar.setText("");
            xkembali.setText("");
            xkd_brg.requestFocus();
            buatnomor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtSimpanActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Apakah ingin keluar dari aplikasi ini?", "Pesan konfirmasi", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    private void xstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xstokActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_xstokActionPerformed

    private void xkd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xkd_brgActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambildata("select * from tbarang where kd_brg='"+xkd_brg.getText()+"'");
            if (rs.next()) {
                xnama_brg.setText(rs.getString("nama_brg"));
                xharga.setText(rs.getString("harga"));
                xstok.setText(rs.getString("jml"));
                xjml.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Kode belum terdaftar");
                xkd_brg.selectAll();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_xkd_brgActionPerformed

    private void xjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjmlActionPerformed
        // TODO add your handling code here:
        int a1, a2, tot, stok_brg = Integer.parseInt(xstok.getText());
        if (stok_brg > 1) {
            a1 = Integer.parseInt(xharga.getText());
            a2 = Integer.parseInt(xjml.getText());
            tot = a1 * a2;
            xjmlh.setText(String.valueOf(tot));
            jbtTambah.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Maaf,\nstok sudah mencapai stok minimum!");
        }
    }//GEN-LAST:event_xjmlActionPerformed

    private void xjmlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xjmlhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xjmlhActionPerformed

    private void jbtTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTambahActionPerformed
        // TODO add your handling code here:
        try {
            int n = JOptionPane.showConfirmDialog(this, "Tambah item lagi?", "RPL Message", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null);
            if (n == JOptionPane.YES_OPTION) {
                long qty, hrg;
                model.addRow(new Object[]{xkd_brg.getText(), xnama_brg.getText(), xharga.getText(), xjml.getText()});
                xtable1.setModel(model);
                qty = Long.parseLong(xjml.getText());
                hrg = Long.parseLong(xharga.getText());
                sumTotal += (hrg * qty);
                xtotal.setText(String.valueOf(sumTotal));
                xkd_brg.requestFocus();
                xkd_brg.setText("");
                xnama_brg.setText("");
                xharga.setText("");
                xstok.setText("");
                xjml.setText("");
                xjmlh.setText("");
            } else if (n == JOptionPane.NO_OPTION) {
                long qty, hrg;
                model.addRow(new Object[]{xkd_brg.getText(), xnama_brg.getText(), xharga.getText(), xjml.getText()});
                xtable1.setModel(model);
                qty = Long.parseLong(xjml.getText());
                hrg = Long.parseLong(xharga.getText());
                sumTotal += (hrg * qty);
                xtotal.setText(String.valueOf(sumTotal));
                xkd_brg.setText("");
                xnama_brg.setText("");
                xharga.setText("");
                xjml.setText("");
                xjmlh.setText("");
                xbayar.requestFocus();
            } else {
                xbayar.requestFocus();
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jbtTambahActionPerformed

    private void jbtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBatalActionPerformed

    private void xbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbayarActionPerformed
        // TODO add your handling code here:
        int a1, a2, kemb;
        a1 = Integer.parseInt(xtotal.getText());
        a2 = Integer.parseInt(xbayar.getText());
        kemb = a2 - a1;
        xkembali.setText(String.valueOf(kemb));
        jbtSimpan.requestFocus();
    }//GEN-LAST:event_xbayarActionPerformed

    private void xtable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xtable1MouseClicked
        // TODO add your handling code here:
        try {
            int n = JOptionPane.showConfirmDialog(this, "Anda tidak yakin membatalkan item ini?", "PRL Massage",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
            if (n == JOptionPane.YES_OPTION) {
                model.removeRow(xtable1.getSelectedRow());
                sumTotal = 0;
                int row = xtable1.getRowCount();
                int tot = 0, hrg, jml;
                
                for (int i = 0; i < row; i++) {
                    hrg = Integer.parseInt(xtable1.getValueAt(i, 2).toString());
                    jml = Integer.parseInt(xtable1.getValueAt(i, 3).toString());
                    sumTotal += (hrg * jml);
                }
                xtotal.setText(String.valueOf(tot));
            } else if (n == JOptionPane.NO_OPTION) {
                return;
            } else {
                return;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_xtable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBatal;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtSimpan;
    private javax.swing.JButton jbtTambah;
    private javax.swing.JTextField xbayar;
    private javax.swing.JTextField xharga;
    private javax.swing.JTextField xjml;
    private javax.swing.JTextField xjmlh;
    private javax.swing.JTextField xkd_brg;
    private javax.swing.JTextField xkembali;
    private javax.swing.JTextField xnama_brg;
    private javax.swing.JTextField xno_trans;
    private javax.swing.JTextField xstok;
    private javax.swing.JTable xtable1;
    private javax.swing.JTextField xtanggal;
    private javax.swing.JTextField xtotal;
    // End of variables declaration//GEN-END:variables
}
