/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposdedy;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import sun.security.pkcs11.Secmod;

import java.awt.Dimension;

/**
 *
 * @author Lenovo
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    
    FrmBarang brg=new FrmBarang();
    FrmTrans trans=new FrmTrans();
    ViewPenjualan viwj=new ViewPenjualan();
    public MenuUtama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        Dimension Posisi=Toolkit.getDefaultToolkit().getScreenSize();
        int x=(Posisi.width-this.getWidth())/2;
        int y=(Posisi.height-this.getHeight())/2;
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmBarang = new javax.swing.JMenuItem();
        jmTransJual = new javax.swing.JMenuItem();
        vp = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        detail_trans = new javax.swing.JMenuItem();
        lapor_trans = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jmBarang.setText("Input Data Barang");
        jmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmBarangActionPerformed(evt);
            }
        });
        jMenu1.add(jmBarang);

        jmTransJual.setText("Transaksi Jual");
        jmTransJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTransJualActionPerformed(evt);
            }
        });
        jMenu1.add(jmTransJual);

        vp.setText("View Penjualan");
        vp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vpActionPerformed(evt);
            }
        });
        jMenu1.add(vp);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Laporan");

        detail_trans.setText("Detail Transaksi");
        jMenu4.add(detail_trans);

        lapor_trans.setText("Transaksi");
        lapor_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapor_transActionPerformed(evt);
            }
        });
        jMenu4.add(lapor_trans);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Keluar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBarangActionPerformed
           // TODO add your handling code here:
        if(!brg.isVisible())
            jDesktopPane1.add(brg);
        brg.setVisible(true);
    }//GEN-LAST:event_jmBarangActionPerformed

    private void jmTransJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTransJualActionPerformed
        // TODO add your handling code here:
        if(!trans.isVisible())
            jDesktopPane1.add(trans);
        trans.setVisible(true);
    }//GEN-LAST:event_jmTransJualActionPerformed

    private void lapor_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapor_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lapor_transActionPerformed

    private void vpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vpActionPerformed
        // TODO add your handling code here:
        if(!viwj.isVisible())
            jDesktopPane1.add(viwj);
        viwj.setVisible(true);
    }//GEN-LAST:event_vpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem detail_trans;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmBarang;
    private javax.swing.JMenuItem jmTransJual;
    private javax.swing.JMenuItem lapor_trans;
    private javax.swing.JMenuItem vp;
    // End of variables declaration//GEN-END:variables
}
